set -g @sessionx-bind "w"
set -g @sessionx-zoxide-mode "on"
set -g @sessionx-filter-current "false"
set -g @sessionx-preview-location "top"
set -g @sessionx-preview-ratio "75%"
set -g @sessionx-tmuxinator-mode "on"
set -g @sessionx-bind-tmuxinator-list "ctrl-p"
set -g @sessionx-filtered-sessions "floax"
