gui:
  expandFocusedSidePanel: true
  nerdFontsVersion: "3"
  border: "rounded" # one of 'single' | 'double' | 'rounded' | 'hidden'
  scrollPastBottom: false
  authorColors:
    "Stavros": "#f47b20"
  scrollHeight: 4 # how many lines you scroll by
  showListFooter: false # for seeing the '5 of 20' message in list panels
  showCommandLog: false
  showBottomLine: false # for hiding the bottom information line (unless it has important information to tell you)

  # testing
  scrollOffMargin: 2 # how many lines to keep before/after the cursor when it reaches the top/bottom of the view; see 'Scroll-off Margin' section below
  scrollOffBehavior: "margin" # one of 'margin' | 'jump'; see 'Scroll-off Margin' section below
  mainPanelSplitMode: "flexible" # one of 'horizontal' | 'flexible' | 'vertical'
  commitLength:
    show: true
  showPanelJumps: false # for showing the jump-to-panel keybindings as panel subtitles
  portraitMode: "auto" # one of 'auto' | 'never' | 'always'
os:
  editPreset: "nvim"
git:
  log:
    # TODO
    # one of date-order, author-date-order, topo-order or default.
    # topo-order makes it easier to read the git log graph, but commits may not
    # appear chronologically. See https://git-scm.com/docs/git-log#_commit_ordering
    order: "topo-order"
    showGraph: "always"
  parseEmoji: true
confirmOnQuit: true
quitOnTopLevelReturn: true
