# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  expandFocusedSidePanel: true
  nerdFontsVersion: "3"
  border: "rounded"
  scrollPastBottom: true
  authorColors:
    "Stavros": "#f47b20"
  scrollHeight: 4
  showListFooter: false
  showCommandLog: false
  showBottomLine: false
  showPanelJumps: false
  scrollOffMargin: 4
  mouseEvents: true
os:
  editPreset: "nvim"
promptToReturnFromSubprocess: false
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  log:
    showGraph: "always"
  parseEmoji: true
confirmOnQuit: true
quitOnTopLevelReturn: true
