# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  expandFocusedSidePanel: true
  nerdFontsVersion: "3"
  border: "rounded"
  scrollPastBottom: true
  authorColors:
    "Stavros Nikoletopoulos": "#f47b20"
    "*": "#b4befe"
  scrollHeight: 4
  showListFooter: false
  showCommandLog: false
  showBottomLine: false
  tabWidth: 2
  showPanelJumps: false
  scrollOffMargin: 4
  mouseEvents: true
  theme:
    activeBorderColor:
      - "#cba6f7"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#392E45"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#cba6f7"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
os:
  editPreset: "nvim"
promptToReturnFromSubprocess: false
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  log:
    showGraph: "always"
  parseEmoji: true
confirmOnQuit: true
quitOnTopLevelReturn: true
